countries_dict = {
    "Andorra": "AD", 
    "United Arab Emirates": "AE", 
    "Afghanistan": "AF", 
    "Antigua and Barbuda": "AG", 
    "Anguilla": "AI", 
    "Albania": "AL", 
    "Armenia": "AM", 
    "Angola": "AO", 
    "Antarctica": "AQ", 
    "Argentina": "AR", 
    "American Samoa": "AS", 
    "Austria": "AT", 
    "Australia": "AU", 
    "Aruba": "AW", 
    "Aland Islands": "AX", 
    "Azerbaijan": "AZ", 
    "Bosnia and Herzegovina": "BA", 
    "Barbados": "BB", 
    "Bangladesh": "BD", 
    "Belgium": "BE", 
    "Burkina Faso": "BF", 
    "Bulgaria": "BG", 
    "Bahrain": "BH", 
    "Burundi": "BI", 
    "Benin": "BJ", 
    "Saint Barthelemy": "BL", 
    "Bermuda": "BM", 
    "Brunei Darussalam": "BN", 
    "Plurinational State of Bolivia": "BO", 
    "Bonaire, Sint Eustatius and Saba": "BQ", 
    "Brazil": "BR", 
    "Bahamas": "BS", 
    "Bhutan": "BT", 
    "Bouvet Island": "BV", 
    "Botswana": "BW", 
    "Belarus": "BY", 
    "Belize": "BZ", 
    "Canada": "CA", 
    "Cocos (Keeling) Islands": "CC", 
    "Democratic Republic of the Congo": "CD", 
    "Central African Republic": "CF", 
    "Congo": "CG", 
    "Switzerland": "CH", 
    "Cote d'Ivoire": "CI", 
    "Cook Islands": "CK", 
    "Chile": "CL", 
    "Cameroon": "CM", 
    "China": "CN", 
    "Colombia": "CO", 
    "Costa Rica": "CR", 
    "Cuba": "CU", 
    "Cabo Verde": "CV", 
    "Curacao": "CW", 
    "Christmas Island": "CX", 
    "Cyprus": "CY", 
    "Czechia": "CZ", 
    "Germany": "DE", 
    "Djibouti": "DJ", 
    "Denmark": "DK", 
    "Dominica": "DM", 
    "Dominican Republic": "DO", 
    "Algeria": "DZ", 
    "Ecuador": "EC", 
    "Estonia": "EE", 
    "Egypt": "EG", 
    "Western Sahara": "EH", 
    "Eritrea": "ER", 
    "Spain": "ES", 
    "Ethiopia": "ET", 
    "Finland": "FI", 
    "Fiji": "FJ", 
    "Falkland Islands (Malvinas)": "FK", 
    "Federated States of Micronesia": "FM", 
    "Faroe Islands": "FO", 
    "France": "FR", 
    "Gabon": "GA", 
    "United Kingdom of Great Britain and Northern Ireland": "GB", 
    "Grenada": "GD", 
    "Georgia": "GE", 
    "French Guiana": "GF", 
    "Guernsey": "GG", 
    "Ghana": "GH", 
    "Gibraltar": "GI", 
    "Greenland": "GL", 
    "Gambia": "GM", 
    "Guinea": "GN", 
    "Guadeloupe": "GP", 
    "Equatorial Guinea": "GQ", 
    "Greece": "GR", 
    "South Georgia and the South Sandwich Islands": "GS", 
    "Guatemala": "GT", 
    "Guam": "GU", 
    "Guinea-Bissau": "GW", 
    "Guyana": "GY", 
    "Hong Kong": "HK", 
    "Heard Island and McDonald Islands": "HM", 
    "Honduras": "HN", 
    "Croatia": "HR", 
    "Haiti": "HT", 
    "Hungary": "HU", 
    "Indonesia": "ID", 
    "Ireland": "IE", 
    "Israel": "IL", 
    "Isle of Man": "IM", 
    "India": "IN", 
    "British Indian Ocean Territory": "IO", 
    "Iraq": "IQ", 
    "Islamic public of Iran": "IR", 
    "Iceland": "IS", 
    "Italy": "IT", 
    "Jersey": "JE", 
    "Jamaica": "JM", 
    "Jordan": "JO", 
    "Japan": "JP", 
    "Kenya": "KE", 
    "Kyrgyzstan": "KG", 
    "Cambodia": "KH", 
    "Kiribati": "KI", 
    "Comoros": "KM", 
    "Saint Kitts and Nevis": "KN", 
    "Democratic People's Republic of Korea": "KP", 
    "Republic of Korea": "KR", 
    "Kuwait": "KW", 
    "Cayman Islands": "KY", 
    "Kazakhstan": "KZ", 
    "Laos People's Democratic Republic": "LA", 
    "Lebanon": "LB", 
    "Saint Lucia": "LC", 
    "Liechtenstein": "LI", 
    "Sri Lanka": "LK", 
    "Liberia": "LR", 
    "Lesotho": "LS", 
    "Lithuania": "LT", 
    "Luxembourg": "LU", 
    "Latvia": "LV", 
    "Libya": "LY", 
    "Morocco": "MA", 
    "Monaco": "MC", 
    "Republic of Moldova": "MD", 
    "Montenegro": "ME", 
    "Saint Martin (French Part)": "MF", 
    "Madagascar": "MG", 
    "Marshall Islands": "MH", 
    "North Macedonia": "MK", 
    "Mali": "ML", 
    "Myanmar": "MM", 
    "Mongolia": "MN", 
    "Macao": "MO", 
    "Northern Mariana Islands": "MP", 
    "Martinique": "MQ", 
    "Mauritania": "MR", 
    "Montserrat": "MS", 
    "Malta": "MT", 
    "Mauritius": "MU", 
    "Maldives": "MV", 
    "Malawi": "MW", 
    "Mexico": "MX", 
    "Malaysia": "MY", 
    "Mozambique": "MZ", 
    "Namibia": "NA", 
    "New Caledonia": "NC", 
    "Niger": "NE", 
    "Norfolk Island": "NF", 
    "Nigeria": "NG", 
    "Nicaragua": "NI", 
    "Netherlands": "NL", 
    "Norway": "NO", 
    "Nepal": "NP", 
    "Nauru": "NR", 
    "Niue": "NU", 
    "New Zealand": "NZ", 
    "Oman": "OM", 
    "Panama": "PA", 
    "Peru": "PE", 
    "French Polynesia": "PF", 
    "Papua New Guinea": "PG", 
    "Philippines": "PH", 
    "Pakistan": "PK", 
    "Poland": "PL", 
    "Saint Pierre and Miquelon": "PM", 
    "Pitcairn": "PN", 
    "Puerto Rico": "PR", 
    "State of Palestine": "PS", 
    "Portugal": "PT", 
    "Palau": "PW", 
    "Paraguay": "PY", 
    "Qatar": "QA", 
    "Reunion": "RE", 
    "Romania": "RO", 
    "Serbia": "RS", 
    "Russian Federation": "RU", 
    "Rwanda": "RW", 
    "Saudi Arabia": "SA", 
    "Solomon Islands": "SB", 
    "Seychelles": "SC", 
    "Sudan": "SD", 
    "Sweden": "SE", 
    "Singapore": "SG", 
    "Saint Helena, Ascension and Tristan da Cunha": "SH", 
    "Slovenia": "SI", 
    "Svalbard and Jan Mayen": "SJ", 
    "Slovakia": "SK", 
    "Sierra Leone": "SL", 
    "San Marino": "SM", 
    "Senegal": "SN", 
    "Somalia": "SO", 
    "Suriname": "SR", 
    "South Sudan": "SS", 
    "Sao Tome and Principe": "ST", 
    "El Salvador": "SV", 
    "Sint Maarten (Dutch part)": "SX", 
    "Syrian Arab Republic": "SY", 
    "Eswatini": "SZ", 
    "Turks and Caicos Islands": "TC", 
    "Chad": "TD", 
    "French Southern Territories": "TF", 
    "Togo": "TG", 
    "Thailand": "TH", 
    "Tajikistan": "TJ", 
    "Tokelau": "TK", 
    "Timor-Leste": "TL", 
    "Turkmenistan": "TM", 
    "Tunisia": "TN", 
    "Tonga": "TO", 
    "Turkey": "TR", 
    "Trinidad and Tobago": "TT", 
    "Tuvalu": "TV", 
    "Taiwan": "TW", 
    "United Republic of Tanzania": "TZ", 
    "Ukraine": "UA", 
    "Uganda": "UG", 
    "United States Minor Outlying Islands": "UM", 
    "United States of America": "US", 
    "Uruguay": "UY", 
    "Uzbekistan": "UZ", 
    "Holy See": "VA", 
    "Saint Vincent and the Grenadines": "VC", 
    "Bolivarian Republic of Venezuela": "VE",
    "Virgin Islands (British)": "VG", 
    "Virgin Islands (U.S.)": "VI", 
    "Vietnam": "VN", 
    "Vanuatu": "VU", 
    "Wallis and Futuna": "WF", 
    "Samoa": "WS", 
    "Yemen": "YE", 
    "Mayotte": "YT", 
    "South Africa": "ZA", 
    "Zambia": "ZM", 
    "Zimbabwe": "ZW"
}

continents_dict = {
    "Africa": "002",
    "Americas":"019",
    "Asia": "142",
    "Europe": "150",
    "Oceania": "009"
}

continents_rev_dict = {
    "002": "Africa",
    "019": "Americas",
    "142": "Asia",
    "150": "Europe",
    "009": "Oceania"
}

subcontinents_dict = {
    "Eastern Africa": "014",
    "Middle Africa": "017",
    "Northern Africa": "015",
    "Southern Africa": "018",
    "Western Africa": "011",
    "Caribbean": "029",
    "Central America": "013",
    "Northern America": "021",
    "South America": "005",
    "Central Asia": "143",
    "Eastern Asia": "030",
    "Southern Asia": "034",
    "Southeastern Asia": "035",
    "Western Asia": "145",
    "Eastern Europe": "151",
    "Northern Europe": "154",
    "Southern Europe": "039",
    "Western Europe": "155",
    "Australia and New Zeland": "053",
    "Melanesia": "054",
    "Micronesia": "057",
    "Polynesia": "061"
}

subcontinents_rev_dict = {
        "014": "Eastern Africa", 
        "017": "Middle Africa", 
        "015": "Northern Africa", 
        "018": "Southern Africa", 
        "011": "Western Africa", 
        "029": "Caribbean", 
        "013": "Central America", 
        "021": "Northern America", 
        "005": "South America", 
        "143": "Central Asia", 
        "030": "Eastern Asia", 
        "034": "Southern Asia", 
        "035": "Southeastern Asia", 
        "145": "Western Asia", 
        "151": "Eastern Europe", 
        "154": "Northern Europe", 
        "039": "Southern Europe", 
        "155": "Western Europe", 
        "053": "Australia and New Zeland", 
        "054": "Melanesia", 
        "057": "Micronesia", 
        "061": "Polynesia"
}

provinces_dict = {
    "Alabama": "US-AL", 
    "Alaska": "US-AK", 
    "Arizona": "US-AZ", 
    "Arkansas": "US-AR", 
    "California": "US-CA", 
    "Colorado": "US-CO", 
    "Connecticut": "US-CT", 
    "Delaware": "US-DE", 
    "Florida": "US-FL", 
    "Georgia": "US-GA", 
    "Hawaii": "US-HI", 
    "Idaho": "US-ID", 
    "Illinois": "US-IL", 
    "Indiana": "US-IN", 
    "Iowa": "US-IA", 
    "Kansas": "US-KS", 
    "Kentucky": "US-KY", 
    "Louisiana": "US-LA", 
    "Maine": "US-ME", 
    "Maryland": "US-MD", 
    "Massachusetts": "US-MA", 
    "Michigan": "US-MI", 
    "Minnesota": "US-MN", 
    "Mississippi": "US-MS", 
    "Missouri": "US-MO", 
    "Montana": "US-MT", 
    "Nebraska": "US-NE", 
    "Nevada": "US-NV", 
    "New Hampshire": "US-NH", 
    "New Jersey": "US-NJ", 
    "New Mexico": "US-NM", 
    "New York": "US-NY", 
    "North Carolina": "US-NC", 
    "North Dakota": "US-ND", 
    "Ohio": "US-OH", 
    "Oklahoma": "US-OK", 
    "Oregon": "US-OR", 
    "Pennsylvania": "US-PA", 
    "Rhode Island": "US-RI", 
    "South Carolina": "US-SC", 
    "South Dakota": "US-SD", 
    "Tennessee": "US-TN", 
    "Texas": "US-TX", 
    "Utah": "US-UT", 
    "Vermont": "US-VT", 
    "Virginia": "US-VA", 
    "Washington": "US-WA", 
    "West Virginia": "US-WV", 
    "Wisconsin": "US-WI", 
    "Wyoming": "US-WY", 
    "District of Columbia": "US-DC", 
}

provinces_rev_dict = {
        "US-AL": "Alabama", 
        "US-AK": "Alaska", 
        "US-AZ": "Arizona", 
        "US-AR": "Arkansas", 
        "US-CA": "California", 
        "US-CO": "Colorado", 
        "US-CT": "Connecticut", 
        "US-DE": "Delaware", 
        "US-FL": "Florida", 
        "US-GA": "Georgia", 
        "US-HI": "Hawaii", 
        "US-ID": "Idaho", 
        "US-IL": "Illinois", 
        "US-IN": "Indiana", 
        "US-IA": "Iowa", 
        "US-KS": "Kansas", 
        "US-KY": "Kentucky", 
        "US-LA": "Louisiana", 
        "US-ME": "Maine", 
        "US-MD": "Maryland", 
        "US-MA": "Massachusetts", 
        "US-MI": "Michigan", 
        "US-MN": "Minnesota", 
        "US-MS": "Mississippi", 
        "US-MO": "Missouri", 
        "US-MT": "Montana", 
        "US-NE": "Nebraska", 
        "US-NV": "Nevada", 
        "US-NH": "New Hampshire", 
        "US-NJ": "New Jersey", 
        "US-NM": "New Mexico", 
        "US-NY": "New York", 
        "US-NC": "North Carolina", 
        "US-ND": "North Dakota", 
        "US-OH": "Ohio", 
        "US-OK": "Oklahoma", 
        "US-OR": "Oregon", 
        "US-PA": "Pennsylvania", 
        "US-RI": "Rhode Island", 
        "US-SC": "South Carolina", 
        "US-SD": "South Dakota", 
        "US-TN": "Tennessee", 
        "US-TX": "Texas", 
        "US-UT": "Utah", 
        "US-VT": "Vermont", 
        "US-VA": "Virginia", 
        "US-WA": "Washington", 
        "US-WV": "West Virginia", 
        "US-WI": "Wisconsin", 
        "US-WY": "Wyoming", 
        "US-DC": "District of Columbia"
}
